### ISSUE TITLE
Adjustable volume slider/config

### ISSUE THREAD

**Issue by humbertovnavarro** [Commandcracker/YouCube#53]
### Describe the feature.

There is currently no way to adjust the range/volume of speakers.

**Comment by Commandcracker** [comment]
### First of all

- The range cant be changed.
- The Volume can only be decreased.
  - (by default the volume is set to `1` and the max volume is `1`)
 - The speaker functions like the [playsound command](https://www.digminecraft.com/game_commands/playsound_command.php)
- The speaker keeps the last volume that it has been set to

The volume can be changed like this:

```lua
local speaker = peripheral.find("speaker")
speaker.playAudio({0},1)
```

Reference [speaker.playAudio](https://tweaked.cc/peripheral/speaker.html#v:playAudio)

Because the speaker keeps the last volume and YouCube doesn't change the volume,
Running YouCube with changed volume is possible.

_Note: volume support has already been mentioned in #18_ 

I'm currently working on an CLI [#2] for YC, when it is finished there will be an argument to change the volume!
For this, I'm creating a custom version of [luarocks argparser](https://github.com/luarocks/argparse) with auto-complication for the ComputerCraft shell.
