### ISSUE TITLE
[youcube.lua] accept cli args

### ISSUE THREAD

**Issue by TheAlan404** [Commandcracker/YouCube#55]
### Describe the feature.

Simple feature: allows you do input urls

`youcube [url]`

Skip `read()` if url is given

Useful for other programs using youcube etc (cough like my ipod thingy)

**Comment by Commandcracker** [comment]
I'm currently working on a "Real" CLI:

![Screenshot_20221203_140436](https://user-images.githubusercontent.com/49335821/205442356-015feb33-9d25-4aa7-a47b-36821a8b7a32.png)


> Useful for other programs using youcube etc (cough like my ipod thingy)

other programs should use [youcubeapi.lua](https://github.com/Commandcracker/YouCube/blob/main/client/lib/youcubeapi.lua)
i will add something like a function called easyPlay that makes integrating YC easier.
Currently creating an app that integrates YC is a bit hard because YC is in **Proof of concept**,
There will be updates that will break your integration!
An example for that is musicify, there YC support is currently broken.

**Comment by Commandcracker** [comment]
I should make it play [dQw4w9WgXcQ](https://www.youtube.com/watch?v=dQw4w9WgXcQ), when no URL is given XD

**Comment by TheAlan404** [comment]
lmao, well somehow my installation doesnt check for args, weird (also i know that link)
